### PR TITLE
Bump NWjs and ffmpeg libraries to 0.68.1, Node to 16.17.0

### PR DESCRIPTION
**Pull request by haslinghuis**
Bump early as there is a bug currently not able to open log files with uppercase extensions.

Fixes: https://github.com/betaflight/blackbox-log-viewer/issues/587#issuecomment-1189015884

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by meoso** [comment]
> Do you want to test this code? Here you have an automated build:  [Betaflight-Blackbox-Explorer-Linux](https://github.com/betaflight/blackbox-log-viewer/suites/7429761659/artifacts/303494426)
 
Ubuntu 20.04.5 LTS: 
* portable version works 100%
* .deb package: 
```
$ /opt/betaflight/betaflight-blackbox-explorer/betaflight-blackbox-explorer 
/opt/betaflight/betaflight-blackbox-explorer/betaflight-blackbox-explorer: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory
```
 Debian 11 (Stable): 
 * Portable version works, with exception of video-export. (see below)
 * .deb package: ZST compression problem : can be rebuilt to XY, compression, so i did, but upon install, it has the **chmod file-rights incorrectly set**, just the same as configurator had during other nwjs stages.
 
 Video export on Debian 11:
 * release & this build fails video-export dialog with this message: `[212733:212755:0831/083926.977149:ERROR:select_file_dialog_impl_portal.cc(698)] Portal returned error: org.freedesktop.portal.Error.InvalidArgument: invalid filter: name is empty`

**Comment by haslinghuis** [comment]
>     used yarn gulp release --linux64 locally on Debian 11, installed package. fails with /opt/betaflight/betaflight-blackbox-explorer/betaflight-blackbox-explorer: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory
>    /opt/betaflight/betaflight-blackbox-explorer/lib/libnw.so does exist; unsure why the error.

> Video export on Debian 11:

>    release 0.3.6 & this build fails video-export dialog with this message: [212733:212755:0831/083926.977149:ERROR:select_file_dialog_impl_portal.cc(698)] Portal returned error: org.freedesktop.portal.Error.InvalidArgument: invalid filter: name is empty

@meoso please check on nwjs 0.67.1 now ffmpeg libraries are available.

**Comment by meoso** [comment]
> @meoso please check on nwjs 0.67.1 now ffmpeg libraries are available.

Tuesday before i can test on Debian, ty.

**Comment by meoso** [comment]
14f8bb9

#### Ubuntu 20.04.5 LTS
* Portable works including video-export with only the following: `[128080:128089:0906/080226.179012:ERROR:cert_verify_proc_builtin.cc(612)] No net_fetcher for performing AIA chasing.`
* .deb package fails to execute with the following: `/opt/betaflight/betaflight-blackbox-explorer/betaflight-blackbox-explorer: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory`


#### Debian GNU/Linux 11 (bullseye)
* Portable works mostly works. Failing video-export.
   - video driver init fail
   - no export due, no save-as dialog.
```
$ ./betaflight-blackbox-explorer 
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[1500421:1500429:0906/075331.647163:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
[1500421:1500429:0906/075331.647456:ERROR:cert_verify_proc_builtin.cc(612)] No net_fetcher for performing AIA chasing.
[1500421:1500429:0906/075344.134297:ERROR:cert_verify_proc_builtin.cc(612)] No net_fetcher for performing AIA chasing.
[1500387:1500410:0906/075347.098626:ERROR:select_file_dialog_linux_portal.cc(719)] Portal returned error: org.freedesktop.portal.Error.InvalidArgument: invalid filter: name is empty
```
* Automated build ZST issue remains.
* Local package build: `/opt/betaflight/betaflight-blackbox-explorer/betaflight-blackbox-explorer: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory`

**Comment by meoso** [comment]
tested only the linux portable `fa30df1` on Debian 11, fails to even open BBL file -- can select files, but nothing happens.
```
$ ./betaflight-blackbox-explorer 
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[503926:503930:0914/075029.723654:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
[503926:503930:0914/075029.724856:ERROR:cert_verify_proc_builtin.cc(612)] No net_fetcher for performing AIA chasing.
```

**Comment by haslinghuis** [comment]
@meoso Ubuntu 2204 is working here. What is the output of `vainfo`?

https://askubuntu.com/questions/1395620/chrome-libva-error-usr-lib-x86-64-linux-gnu-dri-ihd-drv-video-so-init-failed

**Comment by meoso** [comment]
i can't be the only one on Debian, but if a am, i certainly dont want to stall production.
```
$ vainfo 
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
```

**Comment by meoso** [comment]
My graphics driver issue repaired (TY for link).  But it remains about the failure to open files on both Debian 11 and Ubuntu 20.04.5 LTS.

**Comment by meoso** [comment]
`5f1e1ea7`

#### Ubuntu 20.04.5 LTS:
- Portable: works 100%
- installed .deb package: fails with same `libnw.so` issue.

#### Debian 11:
- all the same old problems, nothing resolved.

Out of scope, but maybe consider `AppImage` for distribution compatibility.

**Pull request merged**
