### PR TITLE
Bump NW.js and ffpmeg library to 0.62.2 and Node to 16.15.1

### PR DESCRIPTION
**Pull request by haslinghuis**
Bump

- NWjs to [0.62.2](https://nwjs.io/blog/v0.62.2/)
- ffmpeg library to [0.62.2](https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases/tag/0.62.2)
- Node to [16.15.1](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V16.md)

https://github.com/nwjs/nw.js/blob/nw62/CHANGELOG.md
https://github.com/actions/virtual-environments

### CODE REVIEW

**Comment by haslinghuis** [comment]
At least configurator still needs `0.62.0` as it's not working with `0.64.0` (on Linux):

Screenshot from 2022-05-20 01-02-27

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by Asizon** [comment]
> At least configurator still needs `0.62.0` as it's not working with `0.64.0` (on Linux):
> 
> Screenshot from 2022-05-20 01-02-27

Nwjs game is started!! @haslinghuis

**Comment by McGiverGim** [comment]
If I'm not wrong, 0.62 had the problem with the square in the drag&drop, and now 0.64 has going worst? Maybe something related to opengl acceleration? Can you try to disable it with `--disable-gpu` to see if the issue is fixed?

**Comment by haslinghuis** [comment]
Configurator on Windows (with or without --disable-gpu):
image

With PR 2916 + NWjs 0.64 is perfect now:
image

**Comment by McGiverGim** [comment]
With 2916 + 0.62 the problem is there under Windows or it needs the 0.64 too? Have you tested the `--disable-gpu` under Linux?

In my Windows I've never seen the OSD as in your capture.

**Comment by haslinghuis** [comment]
On Windows 0.62 is ok, But with 0.64 it needs your fixes in 2916.

Have to find the icon in Linux. It doesn't create one if I install my local release, So will create a PR to grab the release from there.

**Review by McGiverGim — APPROVED** [review]

**Pull request merged**
