### PR TITLE
Fix BaroAlt decoding

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: #611

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by McGiverGim — DISMISSED** [review]

**Comment by KarateBrot** [comment]
I think we should rather fix this naming error in the BF firmware.

**Comment by haslinghuis** [comment]
Sure have looked, but grep didn't find it?

**Comment by KarateBrot** [comment]
I checked and it should be fixed by now. See https://github.com/betaflight/betaflight/pull/11911/files#diff-97bfca89118cc758fd1576b948ef1cbb5f5f03b4c309cd8236af75a776ca22d1R220

Did you maybe use a log that was recorded with an old master?

**Comment by haslinghuis** [comment]
Yes that might be logical conclusion :+1:

**Comment by KarateBrot** [comment]
I think we are not using semver for the blackbox viewer

**Pull request closed without merging**
