### PR TITLE
Fix export video

### LINKED ISSUE #776: Export video button does ntohing -- master
### Describe the bug

Export video button does ntohing -- master

### To Reproduce

click

### Expected behavior

export

### Betaflight Blackbox Explorer version

master

### Add any other context about the problem that you think might be relevant here

Chrome / Firefox
Linux

### PR DESCRIPTION
**Pull request by haslinghuis**
- fixes #776

### CODE REVIEW

**Comment by nerdCopter** [comment]
- seems to be working on chrome (slower than legacy installed BBE and probably not controllable) 
  - caveat: strange percentage oscillation, reproducible (i think it is launching twice, but with only 1 save dialog [uncertain]) : https://youtu.be/5xYjUpyQbqM
- not working on firefox at all:
  - image

**Comment by nerdCopter** [comment]
edited comment

**Comment by haslinghuis** [comment]
- No issue when running locally :upside_down_face: ( you did not double click ? :smile: )
- Firefox not working is a known issue.

**Comment by nerdCopter** [comment]
did not double-click, tested multiple times. it does not seem doubled until about 2/5th or 1/2 through the export.

**Comment by haslinghuis** [comment]
@nerdCopter added alert - please check again

Tested with local and netlify now.

**Comment by nerdCopter** [comment]
one alert. @nerdCopter confused.

**Review by nerdCopter — APPROVED** [review]

**Comment by haslinghuis** [comment]
Removed the second commit. Also noted after stopping playing youtube video it ran twice as fast here.

**Comment by nerdCopter** [comment]
maybe gate for chrome/compatible. alert for non-compatible.

**Pull request merged**
