### PR TITLE
Add dterm stage 2 filter

### PR DESCRIPTION
**Pull request by McGiverGim**
Adds support for new dterm stage 2 filter

### CODE REVIEW

**Comment by mikeller** [comment]
Not sure if we want to merge this now, or wait until we've finalised the filtering in the firmware.

**Comment by McGiverGim** [comment]
Yes, I was not sure neither. If the stage 2 is not sure to be included in 3.4 I think is better to wait.

**Comment by mikeller** [comment]
The decision on that will still have to be made.

**Comment by McGiverGim** [comment]
@mikeller the stage 2 filter has been approved, so I think that now this can be merged :-)

**Comment by mikeller** [comment]
@McGiverGim: Can you please confirm that this is still correct after the removal of filtering options in betaflight/betaflight#5975?

**Comment by McGiverGim** [comment]
@mikeller yes, it is correct. Only the types has been removed and they were never added to the Blackbox. This PR does not modify them and not any new type was introduced.

@fujin Yes, @DieHertz told me the same yesterday in a configurator PR. The problem is that I added the stage 1 and 2 in other PR to the gyro filters. My idea is to merge this as is, to be coherent with actual code, and immediately do a new PR to remove the "stage" word in all places. Is that right or is better to remove it here?

**Pull request merged**
