### PR TITLE
Bump NW.js (0.60.0)

### PR DESCRIPTION
**Pull request by haslinghuis**
Synchronizing with https://github.com/betaflight/betaflight-configurator/pull/2797

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by McGiverGim — APPROVED** [review]

**Comment by haslinghuis** [comment]
@McGiverGim now we have updated configurator - should we update this also now in current release?

**Review by Asizon — APPROVED** [review]

**Review by McGiverGim — APPROVED** [review]
I think yes...

**Pull request merged**
