### PR TITLE
Add revision to taskbar

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by nerdCopter** [comment]
come out as undefined for me, will re-test tomorrow

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by nerdCopter** [comment]
* `const gitRevision = manifest.gitRevision;` is remaining undefined.  something different in BBE vs configurator.
* i do recall trying to do this last year with same results.  i even starting trying to retrieve it via gulpfile (gulp-git) and gave up.

**Comment by nerdCopter** [comment]
i used a breakpoint and a "watch" to copy the object/values. i do not see any gitRevision:
```
{
    "__nwjs_app": true,
    "__nwjs_manifest": {
        "author": "The Betaflight open source project.",
        "chromium-args": "--disable-features=nw2",
        "default_locale": "en",
        "dependencies": {
            "Leaflet.MultiOptionsPolyline": "hgoebl/Leaflet.MultiOptionsPolyline",
            "bootstrap": "~3.4.1",
            "html2canvas": "^1.0.0-rc.5",
            "leaflet": "^1.9.3",
            "leaflet-marker-rotation": "^0.4.0",
            "lodash": "^4.17.21"
        },
        "description": "Crossplatform blackbox analitics tool for Betaflight flight control system.",
        "devDependencies": {
            "@quanle94/innosetup": "^6.0.2",
            "command-exists": "^1.2.8",
            "del": "^5.0.0",
            "gulp": "^4.0.1",
            "gulp-debian": "^0.3.2",
            "gulp-rename": "^2.0.0",
            "gulp-util": "3.0.8",
            "gulp-yarn": "^3.0.0",
            "gulp-zip": "^5.0.0",
            "inflection": "1.12.0",
            "nw-builder": "^3.7.4",
            "os": "^0.1.1",
            "rpm-builder": "^1.0.0",
            "temp": "^0.9.0",
            "through2": "4.0.2",
            "yarn": "^1.22.0"
        },
        "displayName": "Betaflight - Blackbox Explorer",
        "engines": {
            "node": "18.x"
        },
        "license": "GPL-3.0",
        "main": "file:///tmp/.io.nwjs.A66tWb/index.html",
        "name": "betaflight-blackbox-explorer",
        "optionalDependencies": {
            "appdmg": "^0.6.2"
        },
        "repository": {
            "type": "git",
            "url": "github.com/betaflight/blackbox-log-viewer"
        },
        "resolutions": {
            "**/**/lodash.template": "^4.5.0"
        },
        "scripts": {
            "gulp": "gulp",
            "release": "gulp release",
            "start": "gulp debug"
        },
        "version": "3.7.0",
        "window": {
            "icon": "images/bf_icon_128.png",
            "id": "main",
            "min_height": 480,
            "min_width": 930,
            "show": true
        }
    },
    "app": {
        "background": {
            "scripts": [
                "nwjs/default.js"
            ]
        }
    },
    "author": "The Betaflight open source project.",
    "chromium-args": "--disable-features=nw2",
    "current_locale": "en_US",
    "default_locale": "en",
    "dependencies": {
        "Leaflet.MultiOptionsPolyline": "hgoebl/Leaflet.MultiOptionsPolyline",
        "bootstrap": "~3.4.1",
        "html2canvas": "^1.0.0-rc.5",
        "leaflet": "^1.9.3",
        "leaflet-marker-rotation": "^0.4.0",
        "lodash": "^4.17.21"
    },
    "description": "Crossplatform blackbox analitics tool for Betaflight flight control system.",
    "devDependencies": {
        "@quanle94/innosetup": "^6.0.2",
        "command-exists": "^1.2.8",
        "del": "^5.0.0",
        "gulp": "^4.0.1",
        "gulp-debian": "^0.3.2",
        "gulp-rename": "^2.0.0",
        "gulp-util": "3.0.8",
        "gulp-yarn": "^3.0.0",
        "gulp-zip": "^5.0.0",
        "inflection": "1.12.0",
        "nw-builder": "^3.7.4",
        "os": "^0.1.1",
        "rpm-builder": "^1.0.0",
        "temp": "^0.9.0",
        "through2": "4.0.2",
        "yarn": "^1.22.0"
    },
    "displayName": "Betaflight - Blackbox Explorer",
    "engines": {
        "node": "18.x"
    },
    "icons": {
        "128": "images/bf_icon_128.png"
    },
    "license": "GPL-3.0",
    "main": "index.html",
    "name": "betaflight-blackbox-explorer",
    "nw-temp-dir": "/tmp/.io.nwjs.A66tWb",
    "optionalDependencies": {
        "appdmg": "^0.6.2"
    },
    "permissions": [
        "developerPrivate",
        "management",
        "<all_urls>"
    ],
    "repository": {
        "type": "git",
        "url": "github.com/betaflight/blackbox-log-viewer"
    },
    "resolutions": {
        "**/**/lodash.template": "^4.5.0"
    },
    "scripts": {
        "gulp": "gulp",
        "release": "gulp release",
        "start": "gulp debug"
    },
    "version": "3.7.0",
    "window": {
        "icon": "images/bf_icon_128.png",
        "id": "main",
        "min_height": 480,
        "min_width": 930,
        "show": true
    }
}
```

**Comment by haslinghuis** [comment]
Yes not sure where to look next :confused:

**Comment by haslinghuis** [comment]
Using git.raw we retrieve the gitRevision. However local it does not show.

Leaving as reference. Not needed.

            // git.raw([ 'describe', '--tags', '--always' ], function (err2, rev2) {
            //     if (!err2) {
            //         gitRevision = rev2.replace(/(\r\n|\n|\r)/gm,"");
            //     }
            //     callback(done, gitRevision, isReleaseBuild);
            // });

**Pull request closed without merging**
