### PR TITLE
The multi-file spectrum comparison

### PR DESCRIPTION
**Pull request by demvlad**
The continue of #779 #780 PRs.
It is possible to add up to 5 spectrum curves by using spectrum data export and import.
1. Create spectrums what need to compare and export its to CSV by pressing "Export" button
2. Create base spectrum and import other spectrums by pressing "Import" button. It is possible to select several files by one 'Import' action.
3. Look results
4. Clear imported spectrums by pressing "Clear" button.
multyspectrums

### CODE REVIEW

**Comment by demvlad** [comment]
The curves legend will added in the next release.

**Comment by nerdCopter** [comment]
image

**Review by nerdCopter — APPROVED** [review]
- approving for function
- request code-review

**Comment by demvlad** [comment]
> * also allows multi-file import in one selection 🙌

Yes, it is possible to select several files by one 'Open' action.

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
