### PR TITLE
Update to Node 16

### PR DESCRIPTION
**Pull request by haslinghuis**
Update to Node 16 (`v16.15.0 LTS`) in sync with https://github.com/betaflight/betaflight-configurator/pull/2913

### CODE REVIEW

**Comment by haslinghuis** [comment]
Reference: https://nwjs.io/versions.json

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
Going to update to latest LTS 16,15,0 LTS.

image

**Review by McGiverGim — APPROVED** [review]
I suppose this has been tested in our repo. It seems that until merged, here in Betaflight continues using 20.04. But the code seems correct to me.

**Pull request merged**
