### PR TITLE
Move Azure pipelines to Github Actions

### PR DESCRIPTION
**Pull request by McGiverGim**
This moves the CI system from Azure pipelines to Github Actions, like it has been done in the Configurator.

Thanks to @mathiasvr for the original code, this only modifies it slightly.

@blckmn this will need the same changes done in the Configurator before merging:
- Update the branch protection settings for pull requests to require the GitHub Action steps instead of the Azure Pipelines steps
- Add environment secret named REPO_TOKEN with a token having (at least) public_repo privileges

This has been tested in the Configurator, so I think is safe to merge. I have tested it in my repo too before doing the PR.

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Review by Asizon — APPROVED** [review]

**Comment by McGiverGim** [comment]
Pushed a change to add an empty line to the end of files, and mark the nightly as prerelease.

**Review by haslinghuis — DISMISSED** [review]

**Review by Asizon — APPROVED** [review]

**Comment by McGiverGim** [comment]
Removed the prerelease tag...

**Review by haslinghuis — DISMISSED** [review]

**Comment by McGiverGim** [comment]
Go out, stale bot...

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by KarateBrot — DISMISSED** [review]

**Review by Asizon — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Comment by haslinghuis** [comment]
Please don't merge yet.

**Comment by haslinghuis** [comment]
@McGiverGim please rebase (if needed) and push again so we analyze the build (as it's not available anymore)

**Comment by McGiverGim** [comment]
I can't do it tomorrow, but I see the build and the artifacts available.

**Comment by McGiverGim** [comment]
Rebased against master...

**Comment by McGiverGim** [comment]
I don't know why it detects the code duplication. My PR does not touch the files that complains. Maybe SonarCloud has modified the way to detect duplications and for this reason now it appears in this PR.

**Comment by haslinghuis** [comment]
Problem is in 

image

**Review by haslinghuis — DISMISSED** [review]

**Comment by McGiverGim** [comment]
Rebased, the false positive of code duplication continues there...

**Review by haslinghuis — APPROVED** [review]

**Comment by McGiverGim** [comment]
@blckmn it seems some permission is missing for the nightly release. Did you add it as requested on the first message?

**Comment by blckmn** [comment]
> @blckmn it seems some permission is missing for the nightly release. Did you add it as requested on the first message?

Yep - missed that step. Have now added the repo_token.

**Pull request merged**
