### PR TITLE
Update Node.js to 18.14.0 LTS and bump workflow to macos-12

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by nerdCopter — APPROVED** [review]
* worked fine locally on Debian 11 (with exception of video export which was already the case)
* i cannot test macOS build
* how i tested: 
```
nvm install 18.4
nvm use 18.4
rm -rf node_modules/
yarn install --check-files ; yarn gulp clean ; yarn gulp debug
```

**Comment by haslinghuis** [comment]
@ctzsnooze can you check on OSX please

**Review by ctzsnooze — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Works fine with my old Mojave 10.14 Mac firmware - great work guys!

**Pull request merged**
