### PR TITLE
Add rates_type to header

### PR DESCRIPTION
**Pull request by IllusionFpv**
To go with https://github.com/betaflight/betaflight/pull/9703

### CODE REVIEW

**Comment by IllusionFpv** [comment]
Screenshot 2020-04-14 18 08 18

**Comment by IllusionFpv** [comment]
@McGiverGim yes, I'm working on it, I can do it in a separate PR or continue this, what do you think?

**Comment by McGiverGim** [comment]
It depends how fast do you have it. I don't see a problem to do it here but I suppose is better to have it in other PR.

**Comment by IllusionFpv** [comment]
Ok, I'll open another PR

**Pull request merged**
