### PR TITLE
Cache Manifest and Improvements for touch devices

### PR DESCRIPTION
**Pull request by simonbethke**
Added a cache-manifest first, so if this viewer is provided on a server (I'd suggest betaflight.com/blackbox/viewer) it will get stored to the browser cache. Afterwards, the app is available in the browser at that URL even when the device is offline.

Additionally, I added touch-support for scrubbing through the seek-bar and the graph.

And finally some slight layout improvements especially for phones in portrait mode.

### CODE REVIEW

**Comment by mikeller** [comment]
@simonbethke: Keen to try this out. Do you have a pointer to instructions on how to easily (self-) host this for testing?

**Comment by wolkesson** [comment]
I’ve been experimenting with an online version too. It would certainly be very nice feature! I hosted it in nodeJS with Express, but there are easier solutions.
One problem though, is that we would have to go through the hurdle of testing in all major browsers. Or, can we somehow block/check so that only recent versions of Chrome will have access?

**Comment by McGiverGim** [comment]
The online version will not have all the features of the offline version. The extension association with files for example.

By the moment I think is good to have an online version, in this way you can check a log at any computer without needing to install the app. But by the moment we must continue developing the offline version.

The users can check the online version to see if it works, if it has problems with some browsers (I'm pretty sure that yes), etc. Let's see...

**Comment by simonbethke** [comment]
Unfortunately I already introduced a regression. (mouse dragging doesn't work atm)

I know approx. 5% of Git and have no idea of the possibilities. It would be nice if we can have a central place for the online BB-Explorer. Also I think the online one doesn't have to differ code-wise from the old one.

How do you feel about refactoring the code to use a more OOP-like approach?

**Comment by McGiverGim** [comment]
It is always welcome any refactoring, but usually it is a lot of work. We do some parts from time to time. If someone want to push some PR to refactor the code, we will be happy with it :)

**Comment by McGiverGim** [comment]
@mikeller yes, you are right... I let myself go to easily... ;-)

**Comment by simonbethke** [comment]
I think we could still provide the online Version to Chrome user-agents only. Maybe add a hidden Feature, to continue with unsupported Browsers...

**Comment by aguindehi** [comment]
I've split up the changes from this PR into #248 #249 #250 #251 #252 while extending them a bit. I've also untangled them from the mouse code to make sure it does not break any mouse related stuff.

**Comment by mikeller** [comment]
Thanks @aguindehi!

**Comment by McGiverGim** [comment]
@aguindehi how is this PR going? I see you divided it into several others PR. Then this can be closed?

**Comment by aguindehi** [comment]
@McGiverGim Most of my changes have been merged with the other PRs. The Cache Manifest change was not merged as it included a static list of files and that list should be generated automatically. Since I do not know the build system, I was not able to integrate an automatic generation of that list of files. For someone with knowledge of the build system it will be a small exersise to add a function automatically generating the list of files of the release. It would make sense to have such a Cache Manifest file, as it allows a browser using the BBLV via the web to cache the application locally on his accessing device and to use the application offline when it's cached.

**Comment by mikeller** [comment]
@simonbethke: Can this be closed?

**Comment by simonbethke** [comment]
Yea, go ahead please.

**Pull request closed without merging**
