### PR TITLE
Fix error by loading default workspace, addition to #751

### PR DESCRIPTION
**Pull request by demvlad**
The duplicate #751 with one additional: the unused json file are removed
Sorry. Yes, of course, it was wrong functions call order.
I've openned the nightly version and got this error too.

closes https://github.com/betaflight/blackbox-log-viewer/pull/751

### CODE REVIEW

**Comment by nerdCopter** [comment]
something still wrong though.

```
        prefs.get('activeWorkspace', function (id){
            if (id) {
                activeWorkspace = id
            }
            else {
                activeWorkspace = 1
            }
        });
```

will set = `1`, but the title is `1 Roll Std` when defaults to ctsnoozes workspace.  
i think (but not certain) this is why graph does not render until workspace is chosen.
image

**Review by nerdCopter — APPROVED** [review]

**Comment by demvlad** [comment]
> activeWorkspace

The id is not number, but it is string? This is interest. Will check.

**Comment by nerdCopter** [comment]
> @nerdCopter
> 
> The id is not number, but it is string? Yes, of course. The problem is in start value only. Will resolved.

seems to be integer, but i'm failing to fix. there might be a different source of problem and not this. difficult to troublshoot.
always reproducible however, if `clear storage`(clear browser data), then load a BBL.

**Comment by demvlad** [comment]
> seems to be integer, but i'm failing to fix. there might be a different source of problem and not this. difficult to troublshoot. always reproducible however, if `clear storage`(clear browser data), then load a BBL.

Yes,this is integer index, i have got no mistake. Will debug next.

**Comment by demvlad** [comment]
@nerdCopter I suggest to open other PR for default Workspace Id issue.
The current PR is more critical.

**Comment by nerdCopter** [comment]
@haslinghuis , please merge as at least allows for a working BBE

**Comment by demvlad** [comment]
@nerdCopter 
I understand what bug you caught,
I do not see it in NW.js version, what i prefer for debugs till,
but i've checked PWA - wow, i've caught it too! Will researh next...

**Pull request merged**
