### PR TITLE
Web build of blackbox explorer

### PR DESCRIPTION
**Pull request by chmelevskij**
This is attempt to port blackbox explorer to web with final goal it becoming offline PWA.

To try it out in the browser
```
yarn start
```

It will create dev server on `http://loclahost:5173:`

Live

https://blackbox-viewer.netlify.app/

### CODE REVIEW

**Comment by nerdCopter** [comment]
WOW, it mostly works.

issue: 
image
sometimes the zoom icon disappears as well.

issue, but BBE continues to work:
image

Linux, Debian 12, Firefox 115.7.0 ESR:
- video open `.mp4` _works_/plays!
- video export issue: 
image

**Comment by chmelevskij** [comment]
@nerdCopter I'm even surprised that much worked 😆

**Comment by chmelevskij** [comment]
@nerdCopter where is the zoom icon usually located? I don't think I have it on the usual build 🤔
Screenshot 2024-03-03 at 15 42 59

**Comment by haslinghuis** [comment]
After doing graph setup - click on motors for example - then this pops up:

image

click in the upper right corner to get the zoom sliders

image

**Comment by mituritsyn** [comment]
everything works except the button to open a new window, logically it should be hidden, or should open a new tab with explorer.

**Comment by nerdCopter** [comment]
in Chrome, even video export works. save-file comes after the export process.

**Comment by mituritsyn** [comment]
oups have an error

```
graph_map.js:263 Uncaught TypeError: Cannot read properties of undefined (reading 'mapTrailAltitudeColored')
    at MapGrapher.redrawFlightTrail (graph_map.js:263:39)
    at MapGrapher.redrawAll (graph_map.js:252:10)
    at MapGrapher.setCurrentTime (graph_map.js:414:10)
    at animationLoop (main.js:307:24)
```
in linux terminal:

```
$ yarn dev
yarn run v1.22.21
$ vite

  VITE v5.0.12  ready in 399 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
Error: The following dependencies are imported but could not be resolved:

  nw.gui (imported by /media/qw/45F882895DB21671/Git/blackbox-log-viewer/js/main.js)

Are they installed?
    at file:///media/qw/45F882895DB21671/Git/blackbox-log-viewer/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:65506:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///media/qw/45F882895DB21671/Git/blackbox-log-viewer/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:64906:38
^C

```
and after this can't open any log

**Comment by chmelevskij** [comment]
@mituritsyn thanks for looking into it.
Do you know the exact steps to reproduce
```
graph_map.js:263 Uncaught TypeError: Cannot read properties of undefined (reading 'mapTrailAltitudeColored')
    at MapGrapher.redrawFlightTrail (graph_map.js:263:39)
    at MapGrapher.redrawAll (graph_map.js:252:10)
    at MapGrapher.setCurrentTime (graph_map.js:414:10)
    at animationLoop (main.js:307:24)
 ```
 ?

**Comment by nerdCopter** [comment]
We would need a 4.5 with GPS positioning log for testing. (i do not have any)

**Comment by mituritsyn** [comment]
> @mituritsyn thanks for looking into it. Do you know the exact steps to reproduce

Sorry, can't reproduce anymore. I loaded a log, check some functions, then upload another log and got this error. Initially I thought it is related to log, but I can't reproduce this issue with those files anymore

[first btfl_001 (7).txt](https://github.com/betaflight/blackbox-log-viewer/files/14512239/btfl_001.7.txt)

[ second LOG00034.txt](https://github.com/betaflight/blackbox-log-viewer/files/14512231/LOG00034.txt)

**Comment by mituritsyn** [comment]
> We would need a 4.5 with GPS positioning log for testing. (i do not have any)

check second log from comment above

**Comment by chmelevskij** [comment]
@nerdCopter @mituritsyn the map issue should be fixed now.

**Comment by haslinghuis** [comment]
Might be a problem with master - with graph_spectrum - have not checked yet.

image

**Comment by haslinghuis** [comment]
Great work @chmelevskij - working now

**Comment by chmelevskij** [comment]
@haslinghuis fixed on here.

It seems to be a common problem due to how config/settings are handled. essentially race conditions everywhere and sometimes it's hard to spot if you already changed settings.

**Comment by haslinghuis** [comment]
Yes - lot of spaghetti and global vars in this code base. Reworked configurator lexical scoping - but did not find the time yet here.

**Comment by VitroidFPV** [comment]
Successfully loaded file, adding/removing/customizing graphs works, so do all the plots and header tables.

LGTM!

**Review by nerdCopter — DISMISSED** [review]
- approving @`bad87f70`. multiple logs from various pilots, good log, bad logs, gps logs, misc. all worked without crashes.

**Comment by nerdCopter** [comment]
github action build are failing :(

**Comment by chmelevskij** [comment]
would like to retain local/NWjs for now if possible.

To run locally you can do `yarn start` this will start the local development version.

I don't see why we should keep the old one around if this one is working. If someone is really needing it can always revert back the git history and use that.

Will add installable PWA next Sunday

**Review by haslinghuis — APPROVED** [review]

**Comment by haslinghuis** [comment]
Maybe need some _new_ version info:

image

**Review by haslinghuis — APPROVED** [review]

**Comment by demvlad** [comment]
This is error while log file is openned (Windows 10, Google Chrome browser):
main.js:751 Uncaught RangeError: Invalid typed array length: 100
    at new Uint8Array (<anonymous>)
    at reader.onload (main.js:751:64)

**Comment by chmelevskij** [comment]
@demvlad can you please upload accompanying log file?

**Comment by demvlad** [comment]
> @demvlad can you please upload accompanying log file?

I apologize, but i can not repeate this error. All work fine today!

**Comment by mituritsyn** [comment]
is there a way to save workspace? now I have to reload workspace each time I update the page

**Comment by haslinghuis** [comment]
@chmelevskij let's do it. Please rebase so we can merge it.

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
