### PR TITLE
Fix Debian package permissions

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes file permissions for debian package. See also [#3009](https://github.com/betaflight/betaflight-configurator/issues/3009)

### CODE REVIEW

**Comment by haslinghuis** [comment]
@meoso found something about zst compression:

Screenshot from 2022-10-01 02-29-07

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Comment by nerdCopter** [comment]
> Do you want to test this code? Here you have an automated build: [Betaflight-Blackbox-Explorer-Linux](https://github.com/betaflight/blackbox-log-viewer/suites/8561836367/artifacts/382634374) 

`8511be2`:

* Ubuntu 20.04.5: `.deb` installation works 100%.
* Debain 11: `.deb` has `.zst` issue; However, building locally, the resultant `.deb` installation works.

**Review by nerdCopter — APPROVED** [review]

**Comment by howels** [comment]
Confirmed working on Ubuntu 22.04 - more details below.

Interestingly the blackbox explorer has a similar bug but not quite as severe as configurator did. For configurator the main binary was non-executable for non-root users but blackbox explorer is executable. The only thing broken is the `lib` directory files are not readable for non-root which blocks loading of libraries on launch:

```
$ ll /opt/betaflight/betaflight-blackbox-explorer
total 106464
drwxr-xr-x 7 root root     4096 Oct  4 14:39 ./
drwxr-xr-x 4 root root     4096 Oct  4 14:39 ../
-rwxr-xr-x 1 root root  3885495 Sep 28 00:37 betaflight-blackbox-explorer*
-rw-r--r-- 1 root root      350 Sep 28 00:37 betaflight-blackbox-explorer.desktop
-rwx------ 1 root root 26918912 Sep 28 00:37 chrome_crashpad_handler*
-rwx------ 1 root root 12617640 Sep 28 00:37 chromedriver*
-rw-r--r-- 1 root root      268 Sep 28 00:37 copyright
-rw------- 1 root root  6615054 Sep 28 00:37 credits.html
drwxr-xr-x 2 root root     4096 Oct  4 14:39 icon/
-rw------- 1 root root 10451040 Sep 28 00:37 icudtl.dat
drwxr-xr-x 2 root root     4096 Oct  4 14:39 lib/
drwxr-xr-x 2 root root     4096 Oct  4 14:39 locales/
drwxr-xr-x 2 root root     4096 Oct  4 14:39 mime/
-rwx------ 1 root root  3249192 Sep 28 00:37 minidump_stackwalk*
-rwx------ 1 root root  2784160 Sep 28 00:37 nacl_helper*
-rwx------ 1 root root    15544 Sep 28 00:37 nacl_helper_bootstrap*
-rwx------ 1 root root  3933576 Sep 28 00:37 nacl_irt_x86_64.nexe*
-rw------- 1 root root   610516 Sep 28 00:37 nw_100_percent.pak
-rw------- 1 root root   913944 Sep 28 00:37 nw_200_percent.pak
-rwx------ 1 root root 27922640 Sep 28 00:37 nwjc*
drwxr-xr-x 2 root root     4096 Oct  4 14:39 pnacl/
-rw------- 1 root root  8310058 Sep 28 00:37 resources.pak
-rw------- 1 root root   722904 Sep 28 00:37 v8_context_snapshot.bin

$ ll /opt/betaflight/betaflight-blackbox-explorer/lib
total 303468
drwxr-xr-x 2 root root      4096 Oct  4 14:39 ./
drwxr-xr-x 7 root root      4096 Oct  4 14:39 ../
-rwx------ 1 root root   3302472 Sep 28 00:37 libEGL.so*
-rwxr-xr-x 1 root root  18211112 Sep 28 00:37 libffmpeg.so*
-rwx------ 1 root root  30663240 Sep 28 00:37 libGLESv2.so*
-rwx------ 1 root root  31632536 Sep 28 00:37 libnode.so*
-rwx------ 1 root root 195146440 Sep 28 00:37 libnw.so*
-rwx------ 1 root root  29121904 Sep 28 00:37 libvk_swiftshader.so*
-rwx------ 1 root root   2643648 Sep 28 00:37 libvulkan.so.1*
-rw------- 1 root root       107 Sep 28 00:37 vk_swiftshader_icd.json
```
The fix works however - forcing correct permissions everywhere we need them. I reckon something changed in that gulp deployer in the past few months as the 3.6.0 release works ok but 3.7 nightlies are bust.

**Review by howels — APPROVED** [review]
Working correctly on Ubuntu 22.04.

**Comment by nerdCopter** [comment]
@howels , i saw this this output earlier, maybe a source of the issue you mentioned. However `nvm use 16.17.0` fixed it for me.
```
[08:17:25] Starting 'release_linux64_rpm'...
[08:17:38] dpkg-deb: error: maintainer script 'preinst' has bad permissions 644 (must be >=0555 and <=0775)
[08:17:38] 'release_linux64_deb' errored after 13 s
[08:17:38] Error: Command failed: dpkg-deb --build ./release//betaflight-blackbox-explorer_3.7.0_amd64
dpkg-deb: error: maintainer script 'preinst' has bad permissions 644 (must be >=0555 and <=0775)

    at ChildProcess.exithandler (node:child_process:398:12)

```
alluding that `0664` may be needed over `664`.

**Comment by SupaflyFPV** [comment]
Mac Builds works as expected

**Review by ctzsnooze — APPROVED** [review]

**Pull request merged**
