### PR TITLE
bump nw.js to version 0.50.2

### PR DESCRIPTION
**Pull request by TheIsotopes**

### CODE REVIEW

**Review by mikeller — CHANGES_REQUESTED** [review]
This does not work.
Trying to open a video file returns this error:

image

In the future, please test your proposed changes before opening pull requests.

**Comment by TheIsotopes** [comment]
@mikeller sorry, I'm a line of sight flyer and don't use cameras on my frames.

**Comment by mikeller** [comment]
@TheIsotopes: Not sure what you want to say. The fact that you are a line of sight flyer does not change the fact that you are expected to test changes before you submit pull requests, and this should include testing of features that you do not have an interest in.
And this particular issue has been discussed in the past: https://github.com/betaflight/betaflight-configurator/pull/1989

Instructions for the update of the ffmpeg libraries that is often required as part of an update of NW.js: https://github.com/betaflight/blackbox-log-viewer/tree/master/library

**Comment by TheIsotopes** [comment]
closed due to lack of ffmpeg library support

**Pull request closed without merging**
