### PR TITLE
Updated library versions.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by McGiverGim** [comment]
This is not the change that need to update the dll video libraries?

**Comment by mikeller** [comment]
They are already at the latest version, and a test exporting videos in linux worked fine, unless I am wrong and it is not exporting of videos that reuqires the libraries.

**Comment by McGiverGim** [comment]
Is opening a video inside the blackbox, but I suppose they will be used to export too.

**Comment by mikeller** [comment]
Tested, it can open videos as well.

**Pull request merged**
