### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by wetheredge**
Fixes some typos found by https://github.com/crate-ci/typos. Mostly in comments, but a few are user-facing.

If it's wanted, I can add the config file I used.

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]
OMG!!! Thanks!

**Comment by wetheredge** [comment]
Here's the config file:

```toml
# .typos.toml
[files]
extend-exclude = ["css/*.min.css", "js/vendor/**"]

[default.extend-words]
iterm = "iterm"
```

It does have a false-positive on the `ba` in [this script src](https://github.com/betaflight/blackbox-log-viewer/blob/master/index.html#L3070).

It also finds Contoller⇒Controller [here](https://github.com/betaflight/blackbox-log-viewer/blob/master/changelog.html#L313), but I wasn't sure if I should touch past changelog entries.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by haslinghuis** [comment]
Yes please change Contoller => Controller too

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
