### PR TITLE
brighter tooltip background

### PR DESCRIPTION
**Pull request by TheAngularity**
better standout from dark background ... looks much better

### CODE REVIEW

**Comment by GaryKeeble** [comment]
I like the result of this change but I am a little uncertain that we should be changing bootstrap as this is a standard style sheet. If we do change it and then update bootstrap in the future, then we would have to re-apply all the local customisations again.

Do you think it would be better perhaps to add the .tooltip customisations to main.css to override bootstrap where necessary; then we wouldn't have to worry about conflicts at a later stage?

**Comment by TheAngularity** [comment]
i know ... something quick & dirty ... if you can add the .tooltip customisations then it would be better

**Comment by GaryKeeble** [comment]
OK, will do; I'll let you know when I've done it :-)

**Comment by GaryKeeble** [comment]
I've implemented your colours in the master now; thanks.

**Comment by TheAngularity** [comment]
thx ... then closed now

**Pull request closed without merging**
