### PR TITLE
Added building native apps with nw.js

### PR DESCRIPTION
**Pull request by basdelfos**
I've got the basics working, following tasks ~~must be~~ are fixed before final merge.
Uses the same gulp commands as Betaflight Configurator.

1. ~~Icons for macOS do not work yet.~~ [Done]
2. ~~Error when importing video file.~~ [Fixed]
3. Testing on Windows ~~and Linux~~ (build and runtime). [Linux: done]
4. ~~Change Readme.md~~ [Done]
5. ~~Change to correct version number.~~ [Done]

Add. 2; screenshot of error message.
image
The nw.js that we currently use probably doesn't have video codecs. I've tried several formats, AVI, MOV and MP4, all give the same error. Need to investigate more.

### CODE REVIEW

**Comment by basdelfos** [comment]
Note to self: https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.

**Comment by basdelfos** [comment]
Fixed ffmpeg issue (task 2). Nw.js distribution is without ffmpeg video codecs.

@mikeller can you test if you can open video files that are also supported with the chrome app?

**Comment by mikeller** [comment]
@basdelfos: I have never used the Chrome app to load / play videos so I don't have much experience with what video formats work and don't work.
A quick check with a couple of videos I had lying around shows that What works / doesn't work seems to be the same between the Chromium app and the NW.js app.
Also, thanks for taking care of this!

**Comment by basdelfos** [comment]
@mikeller thanks. That also conforms the ffmpeg library works on Linux. Did the app icon also display correct on Linux?

**Comment by mikeller** [comment]
@basdelfos: Checking ... yup, icon looks ok under linux.

**Comment by basdelfos** [comment]
@mikeller I think it is pretty much finished. Only windows needs to be tested, best to release a RC to let beta users test it.

**Comment by basdelfos** [comment]
MacOS DMG image (3.0.0-rc1) can be downloaded here: https://drive.google.com/file/d/1OhMxc4-pw9v2Qggojujx5O6p2MWunSh3/view?usp=sharing

**Comment by mikeller** [comment]
@basdelfos: I gave this a quick spin on linux, and for some reason the app does not start when running `gulp debug`. I traced it to the invocation of `gulp.src(libSrc).pipe(gulp.dest(libDest))`, if this is commented out it will work fine. This makes me suspect that that this somehow modifies the global state, and `runSequence` cannot cope with this. Ideas?

**Comment by basdelfos** [comment]
@mikeller that step is needed to replace the default ffmpeg library with the full ffmpeg library to open/play videos in the logger. Could be that I mixed-up the path. Can you check for me where the ffmpeg library lives when you make a build?

**Comment by mikeller** [comment]
@basdelfos: It does not look like starting the app fails because the `post-build` step fails, that part seems to be working just fine (and the file is in the right place):

```
user@pc:~/git/blackbox-log-viewer$ gulp debug
[...]
Zipping package.json
[08:03:16] Starting 'post-build'...
Copy ffmpeg library to Linux app (./library/linux64/libffmpeg.so to debug/betaflight-blackbox-explorer/linux64/lib/)
[08:03:16] Finished 'post-build' after 9.63 ms
Starting debug app (debug/betaflight-blackbox-explorer/linux64/betaflight-blackbox-explorer)...
[08:03:16] Finished 'debug' after 16 s

user@pc:~/git/blackbox-log-viewer$ ls ./library/linux64/libffmpeg.so 
./library/linux64/libffmpeg.so
```

**Comment by mikeller** [comment]
@basdelfos: Can you please rebase / squash so we can merge this?

**Comment by basdelfos** [comment]
Yes, was thinking of doing that when @DieHertz approves the PR to be merged.

**Comment by AndersHoglund** [comment]
Added a Jenkins job for this project: http://andwho.sytes.net:8080/job/Basdelfos_Blackbox_Log_Viewer/
Only Linux64 and Win32 supported? (And OSx, not built by Jenkins. No such env available.)

**Comment by mikeller** [comment]
@basdelfos: We also still need to look into why the darned debug build does not start the app under linux - but that is quite marginal and can be done after the merge.

**Comment by basdelfos** [comment]
Added update check (same method as betaflight configurator) and squashed commits.

**Comment by basdelfos** [comment]
@mikeller: just setup a linux (ubuntu lts) virtual machine to test the debug build in linux. It seems to start fine after creating the debug build with `gulp debug`. Do you get an error or does is just not start without any notice?

**Comment by mikeller** [comment]
@basdelfos: Yes it is starting fine _after_ the build for me too - it is just that it's not starting as part of the `gulp debug` build - but that's really just a minor annoyance. (One suspicion I have is that it could be because it's trying to start before the lib copy has been completed.)

One more thing I noticed is that under linux, the application icon is showing the default NW.js icon.

**Comment by AndersHoglund** [comment]
CI moved here: http://andwho.sytes.net:8080/job/Borisb_Blackbox_Log_Viewer/ 
Still only for Linux64 and Win32.

**Comment by basdelfos** [comment]
@mikeller I think that #92 could also solve the issue you have about the application icon is not showing the correct application icon under linux.

**Comment by mikeller** [comment]
Hmm, I switched to gnome terminal (ubuntu 17.10) now, and now neither the blackbox log viewer nor the Betaflight configurator do show an icon in the task bar. :confused:

**Comment by basdelfos** [comment]
Hmm, ok, I have an Ubuntu 16.x LTS desktop running in a vm, will check if the icon works for both. I can remember that it did work for the blackbox log viewer.

**Comment by mikeller** [comment]
I am not saying that this is something that was broken in blackbox log viewer. It's probably just that gnome terminal in 17.10 has different constraints to unity in 16.10.

**Comment by basdelfos** [comment]
Oh, with gnome terminal you mean another desktop environment than unity.

**Comment by mikeller** [comment]
Yes. Ubuntu seems to be changing their default very often...

**Comment by McGiverGim** [comment]
@basdelfos where do you get from the library files? It seems I can't find them in internet, I'm searching for a win64 and linux32 version. Thanks!

**Pull request merged**
