### PR TITLE
include timebar with gradient show/hide

### PR DESCRIPTION
**Pull request by nerdCopter**
include vertical timebar with background gradient show/hide option

### CODE REVIEW

**Comment by meoso** [comment]
me #406

**Comment by mikeller** [comment]
@nerdCopter: Can you please add some screen shots of how this looks before / after your change?

**Comment by nerdCopter** [comment]
should also note, that because @wolkesson had set the default false(hide), i changed to true(show) so that regular users are not surprised by no vertical timebar.  

I did notice however, my _first-run_, i had to toggle twice due to local setting already false(hide).

**Comment by wolkesson** [comment]
That’s why I’m not sure it should be the same setting. It’s a good idea to be able to hide it for when you want to export and add the video in post. Don’t see why people don’t want the build in video overlay feature, but not doing much video myself. But I think we want to hide the gradient by default (few people seams to want it) but we don’t want to hide the vertical time line by default. So I would suggest two setting. Or just removing the gradient all together.

**Comment by mikeller** [comment]
Yeah, I am the same as @wolkesson: I can see that the gradient is adding very little in terms of usefulness, whereas the timebar is useful for users wanting to analyse data. So I think it would be better to have independent settings for them, and default the gradient to off, and the timebar to on.

**Comment by nerdCopter** [comment]
either way works for me.  i'm open to your recommends; i'll just stay on my local-compile in the meantime.  Thank you both so very much.

**Comment by meoso** [comment]
ummm **_i am so sorry_**, i meant to force push to my own repo.   i hope i did not screw the pooch

**Pull request merged**
