### PR TITLE
Fixed bug when parsing invalid 'E' frame.

### LINKED ISSUE #245: Analyser not working for a BB logs from BF 3.5RC2
Hi,
analyser is not working in 3.2.0 for a data from BF 3.5RC2. Data from version BF3.4 are working properly.
I can see only blank analyser window there
bb_analyzer

### PR DESCRIPTION
**Pull request by mikeller**
Fixes #245.

### CODE REVIEW

**Comment by McGiverGim** [comment]
I introduced this bug, the GPS frame is invalid I think remember when no GPS Home when take off, but need to be processed to get the rest of the data (number of sats, time...). If not processed the viewer showed frames lost that were not (frame invalid).

**Comment by mikeller** [comment]
Ok, so is my fix correct, or is something more complex needed? What I did was just work around the error.

**Comment by McGiverGim** [comment]
I did the same the other time 😁 the problem is that we need to process the GPS frames but not the others.

**Comment by McGiverGim** [comment]
Until October I can't look at this. So if you want merge it and I will fix the GPS frames later.

**Comment by mikeller** [comment]
@McGiverGim: Thanks. Can you please review this then?

**Comment by McGiverGim** [comment]
Done. It looks good to me.

**Pull request merged**
