### PR TITLE
Add SupaflyFPV graphconfigs as default preset

### PR DESCRIPTION
**Pull request by chmelevskij**
Currently if you load blackbox viewer for the first time it has not workspaces to show. This adds basic workspace configuration from @SupaflyFPV as a default one.

### CODE REVIEW

**Comment by SupaflyFPV** [comment]
Thanks Tom! I think we can have a discussion with @ctzsnooze who [uploaded his template here](https://github.com/betaflight/blackbox-log-viewer/pull/726#issuecomment-2080229055) as what the best default would be....

**Comment by mituritsyn** [comment]
In case my workspace is useful. 
i think for a normal user you should leave only the essentials:
- noise analysis tab, which includes: debug, unfiltered gyro, filtered gyro motors and RPMs
- PID analysis for each axis: P, I, D, setpiont, gyro, FF; PID sum, PID error; motors

This is the minimum set to analyse the log, it should be enough for ordinary users, advanced users will make their own workspace.

[workspaces.json](https://github.com/betaflight/blackbox-log-viewer/files/15138226/workspaces.json)

**Comment by mituritsyn** [comment]
could we give to user a choice of several worspaces, like presets system?

**Comment by chmelevskij** [comment]
> could we give to user a choice of several worspaces, like presets system?

While it sounds nice, someone would need to build that 😜 and it doesn't sound like feature which can be added quickly.

**Comment by demvlad** [comment]
> could we give to user a choice of several worspaces, like presets system?

Why, if we can load any presets from file instead of default.

**Comment by demvlad** [comment]
> Thanks Tom! I think we can have a discussion with @ctzsnooze who [uploaded his template here... as what the best default would be....

This preset is for min-max values control PR only. It will not have effect with current master branch version.

**Comment by mituritsyn** [comment]
> Why, if we can load any presets from file instead of default. 
the problem is that user should find workspace somewhere. with multiple choice they could test different workspaces and choose the one which is better suits their needs. For example give users workspaces from ctzsnoose, UAVTech and Chriss Rosser as static examples, no need to integrate separate github repo for this

**Review by blckmn — APPROVED** [review]

**Comment by blckmn** [comment]
When we have a better default we can change it ... until then :)

**Comment by ctzsnooze** [comment]
@SupaflyFPV could you please put your workspace.json file here?  The one used in this PR?
Otherwise users who already loaded a workspace file, or saved their own settings, cannot easily review your 'default' workspace and can't provide feedback about it.

**Comment by SupaflyFPV** [comment]
[UAV Supafly.json](https://github.com/betaflight/blackbox-log-viewer/files/15206291/UAV.Supafly.json)

**Pull request merged**
