### PR TITLE
Updated dependencies to latest versions.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by McGiverGim** [comment]
It seems something is wrong, at least with my system (Windows 10):
image

I've deleted the `node_modules` folder, and executed a `npm install`. The Blackbox is built without problem, but executing the application I get the error on the image. The `gulp debug` ends without starting the app neither.

**Comment by McGiverGim** [comment]
Maybe we need to update the `lib` folder, I will take a look to it.

**Comment by mikeller** [comment]
Try now.

**Comment by McGiverGim** [comment]
I can't see any change?

**Comment by mikeller** [comment]
*Not* making typos when typing `git push` helps... :wink:

**Pull request merged**
