### PR TITLE
Fixed issues of first applications run

### PR DESCRIPTION
**Pull request by demvlad**
Fixed issue of first program run, when do not exist any saved config data on PC.

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Comment by demvlad** [comment]
@haslinghuis @nerdCopter 
will updated soon.
- the onSwitchWorkspace call optimization
- one new internal "unvisible" issue, when there are no saved graphs configuration by first run

**Comment by nerdCopter** [comment]
it does select `1 Std Roll`; however, it does not apply the workspace as you can see the legend remains blank. this may or may not be the cause of the invisible graphs.

**Comment by demvlad** [comment]
> it does select `1 Std Roll`; however, it does not apply the workspace as you can see the legend remains blank. this may or may not be the cause of the invisible graphs.

Ok. Thank's.  I've studied to clear applications saved config data. The many issues are visible now. The clear programm run have the underwater stounes... Will resolved. I think to change the PR caption.

**Comment by nerdCopter** [comment]
it works!, _**but**_, 
black and white :zany_face: 
image
re-selecting the same produces normal color
image

**Comment by demvlad** [comment]
> it works!, _**but**_, black and white and `Legend`🤪

@nerdCopter 
I am looking this issue too. It seems the last start up issue. Maybe :)
What is your advice: The new PR for it? Or will resolve in this?

**Comment by nerdCopter** [comment]
resolve here please. Thank you very much for your efforts

**Comment by demvlad** [comment]
> resolve here please. Thank you very much for your efforts

Ok! There are the long train :)

**Comment by nerdCopter** [comment]
just a comment: refactors like commit `279163d` should probably not be included in bugfix/feature PR's.
but can proceed.

**Comment by nerdCopter** [comment]
`d87d37dd`:
- non-DFU conenct fixed.
- `create backup` results in 
image
- `ignore the risk` flashes fine with manual DFU

**Comment by haslinghuis** [comment]
Last comment is probably in the wrong room :)

**Review by nerdCopter — APPROVED** [review]
- it works!
- surprised old code needed mods, or is it just a circumvention?

**Comment by demvlad** [comment]
> * it works!
> * surprised old code needed mods, or is it just a circumvention?

I change the olde code hard in last PR :) There were the one only situation, what i've missed.
But i've found easy solution how to assign auto color for extended curves in  graph_config.js module now.
Maybe i will replace the all color assign code from graph_config_dialog.js to graph_config.js  in future to have it in one place.

**Comment by demvlad** [comment]
The SonarCloud is not calm :). Will check.

**Comment by demvlad** [comment]
There are no SonarCloud issue now! That's all.

**Comment by demvlad** [comment]
I've found  one issue.... Will resolved soon.

**Comment by demvlad** [comment]
Ready!

**Review by haslinghuis — APPROVED** [review]
LGTM

**Review by nerdCopter — APPROVED** [review]

**Comment by demvlad** [comment]
@nerdCopter @haslinghuis 
I've found some strange thing.
This code fragment is duplicated in main.js (in middle and end part) during long time.
Will check how it can be better on next week.

// initial load of the configuration defaults if we have them
        prefs.get('workspaceGraphConfigs', function(item) {
            if (item) {
                workspaceGraphConfigs = upgradeWorkspaceFormat(item);
            } else {
                workspaceGraphConfigs = [];
            }
        });

        prefs.get('activeWorkspace', function (id){
            if (id) {
                activeWorkspace = id
            }
            else {
                activeWorkspace = 1
            }
        });

**Pull request merged**
