### PR TITLE
Ui override in legend

### LINKED ISSUE #167: Expo, Smooth and Grid buttons hide when enough space
If I made the window small enough, the zoom is converted into a menu and some "new" options appear:

image

These options are not available when the window has space enough. This can be fixed adding the buttons in the expanded form, in the same way than there are in the view menu.

I've done it, but my skills in design are very bad, so I ask help for this ;)

@wolkesson you did the reorder or the menu/design, and seems you have experience with this. Have you time to help me with this?

My idea is get rid or this other PR: https://github.com/betaflight/blackbox-log-viewer/pull/161 to do this, I need:
- Get a "decent" design of the new buttons/actual menu.
- Store this and other settings in the chrome storage, in this way they are visible and stored betweens sessions.

What do you think? New images for these "buttons" are the first thing we need.

### PR DESCRIPTION
**Pull request by wolkesson**
Fixes #167 

Images are embedded SVG. 
Removed toolbar dropdown because buttons in the legend are not affected by resizing. 

Would you like me to also remove the status bar texts?

### CODE REVIEW

**Comment by McGiverGim** [comment]
It seems good to me. I will test it today to see how it looks/behave, but the code is good.

About the status bar override, I will see if it has some sense to maintain it after testing your change (I'm pretty sure that not).

Good work!

**Comment by McGiverGim** [comment]
I've tested the changes. Two things:
- Yes, I think we can get rid of the status bar texts.
- To me is strange to have a blue border only in the latest button pressed. Maybe is a good idea to have a border/background when hovering the button (to remark that can be pressed) but not remain there only in the latest pressed button. Another option is to let the border/background in the deactivated buttons (to remark this state). But as I say, not in the latest pressed only.

image

What do you think?

**Comment by wolkesson** [comment]
I agree! **Hold the merge!** 
I'll remove the status bar texts and the blue box. The box is something jQuery adds to all buttons, but I'll remove it and instead add a hover effect indicating that it's clickable, as you suggest. I have a long flight tomorrow night, now I've got some entertainment! :)

**Comment by wolkesson** [comment]
Ok to merge now, if all is good! This fixes #167 and enables further development on #161.

**Comment by McGiverGim** [comment]
It seems good to me, and works perfectly. Good job!!!!

**Pull request merged**
