### PR TITLE
Setting to show/hide background gradient off graph.

### PR DESCRIPTION
**Pull request by wolkesson**
Closes: #406

### CODE REVIEW

**Comment by Docteh** [comment]
Hi @wolkesson , I edited your post, it looks like github does not accept `Closing issue: #406` but it does accept other words, see: [closing issues with keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords)

**Comment by mikeller** [comment]
@wolkesson: Rebasing on latest master should make the SonarCloud complaints go away.

**Comment by wolkesson** [comment]
Tried, but there was nothing to commit... The .sonarcloud.properties file is empty. Anything I should check for? The failing checks are not in files I’ve changed.

**Comment by mikeller** [comment]
@wolkesson: All good then - seem to be a problem with SonarCloud - and it's always only the 'duplicate lines' that are acting up.

**Pull request merged**
