### PR TITLE
[refactor] lexical scoping

### LINKED ISSUE #691: Can't open "Freq vs throttle" plots for some logs after #668
### Describe the bug

Analyzer display doesn't show "Freq vs throttle" data on some logs after #668 
affected fields: gyro, unfiltered_gyro, gyro_scaled maybe other

image

[1.txt](https://github.com/betaflight/blackbox-log-viewer/files/14025399/1.txt)

### To Reproduce

- Open provided log file. not sure if it is matter some fields disabled in BF blackbox tab( setpoint and rc commands are on place ).
- Switch to second log in top right menu.
- Add gyro | unfiltered_gyro |  gyro_scaled  and press on any axis. 
- Analyzer display will appear with no data (it is hard to see need to hover the cursor on bottom left area).

f12 console shows error:

`Cannot plot analyser TypeError: Cannot read properties of undefined (reading '0')      grapher.js:878 `

 For first log it works as expected

### Expected behavior

"Analyzer display" shows gyro data.

### Betaflight Blackbox Explorer version

3.7.0 (master) 

### Add any other context about the problem that you think might be relevant here

_No response_

### PR DESCRIPTION
**Pull request by haslinghuis**
TBD

### CODE REVIEW

**Review by McGiverGim — COMMENTED** [review]
There is no way way to fix this without returning to the old var?

**Comment by haslinghuis** [comment]
Initial it worked but after switching still get

image

**Comment by haslinghuis** [comment]
@McGiverGim agree it's a mess with all the vars imho.

**Comment by nerdCopter** [comment]
`a585376f` no change in behavior for me (still `Cannot plot analyser TypeError: Cannot read properties of undefined (reading '0')` for `Freq vs Throttle`).

**Comment by tbolin** [comment]
I don't think the variable scopes are the problem. There is a possibility that 'vsBinIndex' is 100, which cause an out of bounds array access on line 124 in graph_spectrum_calc.js
bild

**Comment by nerdCopter** [comment]
i put that line inside of try/catch and yes, many errors
image
(reading `200`..`299`)

**Comment by nerdCopter** [comment]
close this in favor of merged https://github.com/betaflight/blackbox-log-viewer/pull/693 correct?

**Comment by haslinghuis** [comment]
Wanted to apply lexical scoping instead.

**Pull request closed without merging**
