### PR TITLE
Adjustment from cleanflight/blackbox-log-viewer

### PR DESCRIPTION
**Pull request by TheAngularity**
- this pr is an cherry pick from cleanflight/blackbox-log-viewer to included all new features and fixes
- it's put betaflight/blackbox-log-viewer on the same stand 
- also it's superseded #56 , #58 , #59 and #62

### CODE REVIEW

**Comment by mikeller** [comment]
Is this a cherry-pick or just a graft?

**Comment by TheAngularity** [comment]
imho it's a chery pick ... what mean graft?

**Comment by McGiverGim** [comment]
Now, the CF log viewer is exactly as BF logviewer with some aditions to solve the new problems/changes. So you can take ALL the changes (but branding) without problem.

**Comment by TheAngularity** [comment]
yes, what i say ... taked all changes but whitout cleanflight branding

**Comment by mikeller** [comment]
- a cherry-pick is when you copy existing changesets into a different branch, preserving their origin. It is done with `git cherry-pick <changeset hash>`.

- a graft is when you copy / paste changes from one branch into another. It destroys history, leads to conflicts on subsequent cherry-picks, and should be avoided at all costs.

From what you are saying, this PR seems to be a graft. It should be redone as a cherry-pick.

**Comment by TheAngularity** [comment]
@mikeller 
i have compared offline the master branches cleanflight with betaflight ... then compared all files in content and changed differents in the betaflight files ... after then forked betaflight/blackbox-log-viewer created a new branch and uploaded the changed files in this branch and make a pull request

**Comment by McGiverGim** [comment]
I don't know if you use eclipse or you are working with commands. In eclipse I add the two repositories to my git repository, create the branch and select one by one the commits from the origin branch to include, right button, cherry pick.

**Comment by TheAngularity** [comment]
@McGiverGim neither ... nor 
i'm used file explorer and notepad ++

**Pull request closed without merging**
