### PR TITLE
Bump NWJS and FFmpeg to 0.83

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by haslinghuis** [comment]
504:

image

**Review by nerdCopter — APPROVED** [review]
- approving. tested UI and video-export successfully.

**Comment by ctzsnooze** [comment]
@haslinghuis @nerdCopter Unfortunately this has broken compatibility with Mac OSX 10.14, the compiled binary simply will not run.

MacOSX14 is quite old but is one of the last versions that still runs intel-only binaries, and some of those programs cannot easily be found in newer MacOSX versions.

Could we revert this change for Mac OSX?  Is it absolutely essential?

**Comment by nerdCopter** [comment]
https://dev.to/thejaredwilcurt/guide-to-nw-js-versions-5d38

**Pull request merged**
