### PR TITLE
Update debug fields

### PR DESCRIPTION
**Pull request by haslinghuis**

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

**Review by nerdCopter — DISMISSED** [review]
* approving untested

**Comment by haslinghuis** [comment]
Sorry have to do a little update:

image

**Review by nerdCopter — APPROVED** [review]
* re-approving. it runs, but i have no BBL with the needed fields to test.

**Comment by haslinghuis** [comment]
Copy pasted from @ctzsnooze  as he asked me to take these in otherwise he needed rebase and more work to do.

**Pull request merged**
