### PR TITLE
Added ALTHOLD flight mode marker at the chart for 4.6 BF firmware

### PR DESCRIPTION
**Pull request by demvlad**
Seems i 've marked my #766 PR as draft only, but it was closed. Never mind...

I've thought, that 766 PR was not helpfull without previouse, what fixed wrong mirrors flight mode issue. This PR include that.

This PR like PR766 add "ALT HOLD" caption for @ctzsnooze  [AltHold #1386](https://github.com/betaflight/betaflight/pull/13816)  Mode at the chart.

### CODE REVIEW

**Comment by demvlad** [comment]
@ctzsnooze @haslinghuis @nerdCopter 
About problem of logging some flight modes.
We have many flight modes in BF Firmware. It total bitmask size more then 32.
But BF writes in log first int32 mask value only. And BBExplorer uses it properly.
The Flight modes with BOX enum indexses more then 32 are missed (acrotrainer and autolaunch for example).
To log these modes and show it in BBE we need rearrange BOX enum list in BF firmware, to place used mode to up 32 instead of unused (USER and similar) and rearrange modes name list in BBExplorer.

**Review by haslinghuis — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Tested just now; alt_hold flag is correct, very nice : thank you!

Only one strange detail that I notice is that the log says `ANGLE OFF | ALT_HOLD ON` whenever Alt_Hold starts, and vice versa when it stops.

In flight, Angle Mode does remain active during Alt Hold, and I don't see anywhere in the firmware where the two are mutually exclusive, so ANGLE should stay ON when ALT_HOLD becomes active, I think.

**Comment by ctzsnooze** [comment]
For testing, it is possible to make test logs containing any flags, just using a flight controller (with a connected Rx and GPS module).  On a working quad, just disconnect the ESC, disable DShot Telemetry, and logs can be made with wild switch changes :-).

**Comment by demvlad** [comment]
> Also, when initiating a GPS RESCUE, the flag says `FAILSAFE ON` not `GPS_RESCUE ON`.

@ctzsnooze 
please, share this log: I am seeing gps rescue mode in log of my drone.
About Angle mode: this is a BF firmware logic. But i have two way to resolve this:
to study and improve BF logic, or to change BBExplorer - add Angle flag directly when auto modes are active.

**Comment by McGiverGim** [comment]
The problem with the flight modes in the past is that the blackbox (including firmware part) only supported 32 elements, and we had more than that. For this reason the modes were wrong. This has been fixed at some moment?

**Comment by demvlad** [comment]
> For this reason the modes were wrong. This has been fixed at some moment?

@McGiverGim @ctzsnooze 
This is the rc modes struct:
typedef enum {
    BOXARM = 0,
    BOXANGLE,
    BOXHORIZON,
    BOXMAG,
    BOXHEADFREE,
    BOXPASSTHRU,
    BOXFAILSAFE,
    BOXGPSRESCUE,
    BOXID_FLIGHTMODE_LAST = BOXGPSRESCUE,

    // RCMODE flags
    BOXANTIGRAVITY,
    BOXHEADADJ,
    BOXCAMSTAB,
    BOXBEEPERON,
    BOXLEDLOW,
    BOXCALIB,
    BOXOSD,
    BOXTELEMETRY,
    BOXSERVO1,
    BOXSERVO2,
    BOXSERVO3,
    BOXBLACKBOX,
    BOXAIRMODE,
    BOX3D,
    BOXFPVANGLEMIX,
    BOXBLACKBOXERASE,
    BOXCAMERA1,
    BOXCAMERA2,
    BOXCAMERA3,
    BOXFLIPOVERAFTERCRASH,
    BOXPREARM,
    BOXBEEPGPSCOUNT,
    BOXVTXPITMODE,
    BOXPARALYZE,

// more then 32 
////////////////////////
    BOXUSER1,
    BOXUSER2,
    BOXUSER3,
    BOXUSER4,
    BOXPIDAUDIO,
    BOXACROTRAINER,
    BOXVTXCONTROLDISABLE,
    BOXLAUNCHCONTROL,
    BOXMSPOVERRIDE,
    BOXSTICKCOMMANDDISABLE,
    BOXBEEPERMUTE,
    BOXREADY,
    BOXLAPTIMERRESET,
    CHECKBOX_ITEM_COUNT
} boxId_e;

Are the mode with more then 32 number realle used and need for logging?
I think, maybe BOXACROTRAINER and BOXLAUNCHCONTROL?
The all modes in top32 list is really need for logging? I think it is not. 
I think, it is not big problem to do global changes in log format

**Comment by demvlad** [comment]
> The correct fix is to modify the blackbox to send/receive more than 32 bit. I looked at it in the past but I didn't like the solution I get.

Ok. Will think how to read these long values  in BBExplirer.

**Comment by demvlad** [comment]
> @ctzsnooze
> 
> Adding `BOXALTHOLD` in `fc/rc_modes.h` might explain why we now see `FAILSAFE` instead of `GPSRESCUE` Perhaps needs to go after GPSRESCUE in line 40 and adjust the following line.
> 

Seems i saw this boxalthold enum in source while was making this PR.

**Comment by demvlad** [comment]
> In flight, Angle Mode does remain active during Alt Hold, and I don't see anywhere in the firmware where the two are mutually exclusive, so ANGLE should stay ON when ALT_HOLD becomes active, I think.

@ctzsnooze 
It can be done in BBExplorer logic easy.
But honestly, i don't know, will easy duplication of althold, gpsrescue with Angle mode helpfull. Yes, i understand that Angle modes algoritms work during navigation modes. But if it works always then why duplicate it at chart. If nav modes will can work manualy without Angle auto, then separate Angle and nav modes draw at chart are really need. But in our case now - i do not know.

**Comment by demvlad** [comment]
The AltHold PR is merged.
I think, this PR can be merged too.

**Comment by demvlad** [comment]
@ctzsnooze @McGiverGim 
Some thoughts about Angle - AltHold,Rescue modes flags behavior in BBExplorer.
We have two modes flags in BF: _BOX and _MODE.
The _BOX flag is set by RC switches state to follow Modes configurator page setup.
The MODES flag is set by using BOX flag and some BF logic conditions. The MODES flag shows flight modes what work really at moment.
But BF logged BOX flags, it is not real MODES. Therefore if we have separately settings of Angle and AltHold modes at Modes configurator tab, then we have our current BBExplorer behavior: Angle off after AltHold on. The AltHold set Angle mode, while AngleBOX flag is off.
I suspect, if we set intersection of AltHold and Angle modes range in configurator Modes page, then we will have BBExplorer flags behavior what we want.
Else we have two other way: improve BF code (make logging of real flight modes), or realize some additional logic in BBExplorer.

**Comment by haslinghuis** [comment]
`ANGLE_MODE` will be enabled when activating `BOXALTHOLD` and disabled when deactivating unless `BOXANGLE` was activated.

https://github.com/betaflight/betaflight/blob/952ccb68c47198ff23ef64e841cdfd2b09f14d0e/src/main/fc/core.c#L973-L987

**Comment by demvlad** [comment]
> `ANGLE_MODE` will be enabled when activating `BOXALTHOLD` and disabled when deactivating unless `BOXANGLE` was activated.
> 

Yes, all right. But ANGLE_BOX is deactivated when   AltHold is on by transmitter switch. And BBExplorer shows Angle off, while it is on really. The BF loggs RC modes state (BOX flag), but it is not real flight mode state.
If some RC mode is locked by BF logic, then probably we will have wrong mode marker in log.
I want to improve flight mode ligging code in BF firmware, to log real flight modes state. I am seeng, it is not difficult code improvement.

**Comment by haslinghuis** [comment]
@demvlad in failsafe tab we show multiple boxes / modes

https://github.com/betaflight/betaflight-configurator/pull/4159

**Pull request merged**
